config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: :index do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates_uniqueness_of :movie_id, scope: [:list_id]
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end
end

  private
    def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>NEW BOOKMARK</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.association :movie %>
<%= f.input :comment %>
<%= f.submit %>
<% end %>
<%= link_to "Back to lists", lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<!DOCTYPE html>
</html>


<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
    <img src="https://cdn.picpng.com/film/film-movie-graphic-symbol-strip-70231.png">
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/lists">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/lists/new">New list</a>
      </li>
    </ul>
  </div>
</div>

<div class="banner vh-100 text-center text-white" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://open-stand.org/wp-content/uploads/2016/04/International-Union-of-Cinemas-Calls-for-Open-Standards-in-the-Cinema-Industry.jpg);">
  <div class="container">
    <h1>Your own Movie Mecca</h1>
  </div>
</div>




<div class="container">
  <h1>My lists</h1>
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category">
        <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container my-5">
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</div>

app/views/lists/show.html.erb
<div class="container my-5">
  <h1 class="my-5">
    <%= @list.name %>
    <%= link_to list_path(@list), method: :delete, data: { confirm: 'Are you sure?'} do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </h1>
  <h2>Movies</h2>
  <% @list.movies.each do |movie| %>
    <p>
      <%= movie.title %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <%= link_to bookmark_path(bookmark.id), method: :delete, data: { confirm: 'Are you sure?'} do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </p>
  <% end %>
  <div class="form my-5">
  <h2>Add a movie!</h2>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :comment %>
      <%= f.association :movie %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
  </div>
</div>